# Generated by Django 5.1.5 on 2025-01-23 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
                ('student_register_number', models.CharField(max_length=20, unique=True)),
                ('student_admission_number', models.CharField(max_length=20, unique=True)),
                ('student_roll_number', models.CharField(max_length=20, unique=True)),
                ('abc_id', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('dob', models.DateField()),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_mobile_number', models.CharField(max_length=15)),
                ('program_id', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapid.course')),
            ],
        ),
    ]
