# Generated by Django 5.1.5 on 2025-01-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapid', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=100, unique=True)),
                ('department_id', models.IntegerField()),
                ('program_level_id', models.IntegerField()),
            ],
        ),
    ]
