# Generated by Django 5.1.5 on 2025-01-23 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapid', '0005_programlevel_role_student_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='course',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='department',
            new_name='department_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='role',
            new_name='role_id',
        ),
    ]
