# Generated by Django 5.1.5 on 2025-01-28 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapid', '0007_remove_user_role_id_alter_teacher_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='abc_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parent_mobile_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parent_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
    ]
