# Generated by Django 5.1.5 on 2025-01-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapid', '0008_remove_student_abc_id_remove_student_course_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='semester',
        ),
        migrations.AddField(
            model_name='course',
            name='year_offered',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
