# Generated by Django 5.1.5 on 2025-01-28 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapid', '0009_remove_course_semester_course_year_offered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='program_level_id',
        ),
        migrations.DeleteModel(
            name='ProgramLevel',
        ),
    ]
