# Generated by Django 5.1.5 on 2025-01-28 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapid', '0010_remove_program_program_level_id_delete_programlevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapid.course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapid.student')),
            ],
        ),
    ]
