# Generated by Django 5.1.5 on 2025-01-28 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapid', '0012_teachercourse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentcourse',
            options={'verbose_name': 'Student Course', 'verbose_name_plural': 'Student Courses'},
        ),
        migrations.AlterUniqueTogether(
            name='studentcourse',
            unique_together={('student_id', 'course_id')},
        ),
        migrations.AlterModelTable(
            name='studentcourse',
            table='student_course',
        ),
    ]
