# Generated by Django 5.1.5 on 2025-01-28 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapid', '0013_alter_studentcourse_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachercourse',
            options={'verbose_name': 'Teacher Course', 'verbose_name_plural': 'Teacher Courses'},
        ),
        migrations.AlterUniqueTogether(
            name='teachercourse',
            unique_together={('teacher_id', 'course_id')},
        ),
        migrations.AlterModelTable(
            name='teachercourse',
            table='teacher_course',
        ),
    ]
