# Generated by Django 5.1.5 on 2025-02-04 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapid', '0016_course_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='strength',
        ),
    ]
