# Generated by Django 5.1.5 on 2025-02-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapid', '0018_remove_course_year_offered'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teachercourse',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='teachercourse',
            name='year',
            field=models.PositiveIntegerField(default=2025, editable=False),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='teachercourse',
            unique_together={('teacher_id', 'course_id', 'year')},
        ),
    ]
