# Generated by Django 5.1.5 on 2025-02-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapid', '0019_alter_teachercourse_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_hod',
            field=models.BooleanField(default=False),
        ),
    ]
