# Generated by Django 5.1.5 on 2025-02-08 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapid', '0020_teacher_is_hod'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourDateCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.PositiveSmallIntegerField(choices=[(1, 'Hour 1'), (2, 'Hour 2'), (3, 'Hour 3'), (4, 'Hour 4'), (5, 'Hour 5')])),
                ('year', models.PositiveIntegerField(editable=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapid.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapid.teacher')),
            ],
            options={
                'unique_together': {('course', 'date', 'hour')},
            },
        ),
        migrations.CreateModel(
            name='AbsentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapid.student')),
                ('hour_date_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rapid.hourdatecourse')),
            ],
            options={
                'unique_together': {('student', 'hour_date_course')},
            },
        ),
    ]
