# Generated by Django 5.1.5 on 2025-03-06 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapid', '0023_remove_student_student_roll_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='gender',
        ),
    ]
